---
title: "README"
output: github_document
auhtor: Jörn Alexander Quent, tweaked by Maris Vainre
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

This R packages includes the [official MRC colour palette](https://mrc.ukri.org/about/information-standards/mrc-brand-guidelines/colour-palette/) spilt into primary and secondary. This package was created following [this](https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2) example.

# Example usage of MRColour
```{r}
library(ggplot2)
library(MRColour)
library(hrbrthemes)

# Primary 
mrc_pal("primary")(3)
mrc_pal("primary")(10)
```

```{r}
# Secondary
mrc_pal("secondary")(3)
mrc_pal("secondary")(10)
```

```{r}
# binary
mrc_pal("binary")(2)
```

```{r}
# greyscale
mrc_pal("greyscale")(3)
mrc_pal("greyscale")(10)
```

```{r}
# ggplot functions
ggplot(mtcars, aes(hp, mpg)) +
  geom_point(color = mrc_cols("red"),
             size = 4, alpha = .8) +
  theme_ipsum(grid=FALSE)
```

```{r}
ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Species)) +
  geom_point(size = 4) +
  scale_color_mrc() +
  theme_ipsum(grid=FALSE)
```

```{r}
iris.sub <- iris %>%
  filter(Species != "versicolor")

ggplot(iris.sub, aes(Sepal.Width, Sepal.Length, color = Species)) +
  geom_point(size = 2) +
  scale_color_mrc(palette = "binary") +
  theme_ipsum(grid=FALSE)
```

```{r}
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_mrc(palette = "primary", guide = "none") +
  theme_ipsum(grid=FALSE, axis_text_size = 6)
```

```{r}
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_mrc(palette = "secondary", guide = "none") +
  theme_ipsum(grid=FALSE, axis_text_size = 6)
```

```{r}
ggplot(mpg, aes(manufacturer, fill = manufacturer)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_mrc(palette = "greyscale", guide = "none") +
  theme_ipsum(grid=FALSE, axis_text_size = 6)
```

